name: Update DGT Map

on:
schedule:
  - cron: '*/3 * * * *' # Triggers an every 3 minutes run
workflow_dispatch: # Adds a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: 
      group: map-update
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("httr", "xml2", "dplyr", "purrr", "tibble", "lubridate", "jsonlite"))'

      - name: Run script
        run: Rscript script.R

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add v16activas.html map_base.html README.md data/*.csv
          git pull --rebase origin main # Important: pulls latest changes before pushing
          git commit -m "Auto-update map: $(date)" || echo "No changes to commit"
          git push origin main
